# -*- coding: utf-8 -*-


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget


class Ui_MainWindow(QWidget):
    def __init__(self):
        super(Ui_MainWindow,self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 551)
        MainWindow.setMinimumSize(QtCore.QSize(500, 350))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_6 = QtWidgets.QSplitter(MainWindow)
        self.splitter_6.setMinimumSize(QtCore.QSize(561, 391))
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_5.setMinimumSize(QtCore.QSize(80, 30))
        self.splitter_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.widget = QtWidgets.QWidget(self.splitter_5)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Account = QtWidgets.QPushButton(self.widget)
        self.pushButton_Account.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_Account.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_Account.setObjectName("pushButton_Account")
        self.horizontalLayout.addWidget(self.pushButton_Account)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(50, 20))
        self.label.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.layoutWidget = QtWidgets.QWidget(self.splitter_5)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_exit_min_sett = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_exit_min_sett.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_exit_min_sett.setObjectName("horizontalLayout_exit_min_sett")
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_exit_min_sett.addItem(spacerItem1)
        self.pushButton_Settings = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Settings.setMinimumSize(QtCore.QSize(31, 31))
        self.pushButton_Settings.setMaximumSize(QtCore.QSize(31, 31))
        self.pushButton_Settings.setObjectName("pushButton_Settings")
        self.horizontalLayout_exit_min_sett.addWidget(self.pushButton_Settings)
        self.pushButton_Minium = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Minium.setMinimumSize(QtCore.QSize(31, 31))
        self.pushButton_Minium.setMaximumSize(QtCore.QSize(31, 31))
        self.pushButton_Minium.setObjectName("pushButton_Minium")
        self.horizontalLayout_exit_min_sett.addWidget(self.pushButton_Minium)
        self.pushButton_Exit = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Exit.setMinimumSize(QtCore.QSize(31, 31))
        self.pushButton_Exit.setMaximumSize(QtCore.QSize(31, 31))
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.horizontalLayout_exit_min_sett.addWidget(self.pushButton_Exit)
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_4.setMinimumSize(QtCore.QSize(541, 351))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_3.setMinimumSize(QtCore.QSize(150, 350))
        self.splitter_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayoutFriendsList = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.horizontalLayoutFriendsList.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutFriendsList.setObjectName("horizontalLayoutFriendsList")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setMinimumSize(QtCore.QSize(150, 30))
        self.label_3.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutFriendsList.addWidget(self.label_3)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayoutFriendsList.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayoutFriendsList.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_3.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayoutFriendsList.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_4.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_4.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayoutFriendsList.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_5.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_5.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayoutFriendsList.addWidget(self.pushButton_5)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_Toolbox = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_Toolbox.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Toolbox.setObjectName("verticalLayout_Toolbox")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setMinimumSize(QtCore.QSize(150, 30))
        self.label_5.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_Toolbox.addWidget(self.label_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_6.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_6.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_Toolbox.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_7.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_7.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_Toolbox.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_8.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_8.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_Toolbox.addWidget(self.pushButton_8)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_10.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_10.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_Toolbox.addWidget(self.pushButton_10)
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_2.setMinimumSize(QtCore.QSize(371, 291))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.listView_Dialog = QtWidgets.QListView(self.splitter_2)
        self.listView_Dialog.setMinimumSize(QtCore.QSize(300, 250))
        self.listView_Dialog.setMaximumSize(QtCore.QSize(900, 900))
        self.listView_Dialog.setObjectName("listView_Dialog")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton_9 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_9.setMinimumSize(QtCore.QSize(60, 30))
        self.pushButton_9.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.textEdit = QtWidgets.QTextEdit(self.splitter)
        self.textEdit.setMinimumSize(QtCore.QSize(300, 30))
        self.textEdit.setMaximumSize(QtCore.QSize(900, 50))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.splitter_6)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UnitAi"))
        self.pushButton_Account.setText(_translate("MainWindow", "头像"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">UnitAi</span></p></body></html>"))
        self.pushButton_Settings.setText(_translate("MainWindow", "设置"))
        self.pushButton_Minium.setText(_translate("MainWindow", "最小化"))
        self.pushButton_Exit.setText(_translate("MainWindow", "关闭"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">好友列表</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">工具箱</span></p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_10.setText(_translate("MainWindow", "模式切换"))
        self.pushButton_9.setText(_translate("MainWindow", "发送"))



if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = Ui_MainWindow()
    w.show()
    sys.exit(app.exec_())